package com.constaapps.constacalc.ui.main;
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Sun May 19 15:02:59 EDT 2019
//----------------------------------------------------

/** CUP v0.10k generated parser.
  * @version Sun May 19 15:02:59 EDT 2019
  */
public class CalcParser extends lr_parser {

  /** Default constructor. */
  public CalcParser() {super();}

  /** Constructor which sets the default scanner. */
  public CalcParser(Scanner s) {super(s);}

  /** Production table. */
  protected static final short _production_table[][] = 
    unpackFromStrings(new String[] {
    "\000\026\000\002\003\005\000\002\002\004\000\002\003" +
    "\005\000\002\003\005\000\002\003\005\000\002\003\005" +
    "\000\002\003\006\000\002\003\006\000\002\003\006\000" +
    "\002\003\006\000\002\003\006\000\002\003\006\000\002" +
    "\003\005\000\002\003\005\000\002\003\006\000\002\003" +
    "\006\000\002\003\006\000\002\003\004\000\002\003\005" +
    "\000\002\003\003\000\002\003\003\000\002\003\003" });

  /** Access to production table. */
  public short[][] production_table() {return _production_table;}

  /** Parse-action table. */
  protected static final short[][] _action_table = 
    unpackFromStrings(new String[] {
    "\000\074\000\034\010\017\012\010\013\005\014\006\015" +
    "\004\016\020\017\012\022\021\023\011\024\016\025\014" +
    "\026\013\031\007\001\002\000\004\010\074\001\002\000" +
    "\004\010\071\001\002\000\004\010\066\001\002\000\026" +
    "\002\uffec\004\uffec\005\uffec\006\uffec\007\uffec\011\uffec\020" +
    "\uffec\021\uffec\027\uffec\030\uffec\001\002\000\004\010\063" +
    "\001\002\000\026\002\uffed\004\uffed\005\uffed\006\uffed\007" +
    "\uffed\011\uffed\020\uffed\021\uffed\027\uffed\030\uffed\001\002" +
    "\000\004\010\060\001\002\000\004\010\055\001\002\000" +
    "\004\010\052\001\002\000\024\002\051\004\027\005\024" +
    "\006\032\007\025\020\034\021\033\027\026\030\030\001" +
    "\002\000\004\010\046\001\002\000\034\010\017\012\010" +
    "\013\005\014\006\015\004\016\020\017\012\022\021\023" +
    "\011\024\016\025\014\026\013\031\007\001\002\000\004" +
    "\010\022\001\002\000\026\002\uffee\004\uffee\005\uffee\006" +
    "\uffee\007\uffee\011\uffee\020\uffee\021\uffee\027\uffee\030\uffee" +
    "\001\002\000\034\010\017\012\010\013\005\014\006\015" +
    "\004\016\020\017\012\022\021\023\011\024\016\025\014" +
    "\026\013\031\007\001\002\000\024\004\027\005\024\006" +
    "\032\007\025\011\031\020\034\021\033\027\026\030\030" +
    "\001\002\000\034\010\017\012\010\013\005\014\006\015" +
    "\004\016\020\017\012\022\021\023\011\024\016\025\014" +
    "\026\013\031\007\001\002\000\034\010\017\012\010\013" +
    "\005\014\006\015\004\016\020\017\012\022\021\023\011" +
    "\024\016\025\014\026\013\031\007\001\002\000\026\002" +
    "\ufff0\004\ufff0\005\ufff0\006\ufff0\007\ufff0\011\ufff0\020\ufff0" +
    "\021\ufff0\027\ufff0\030\ufff0\001\002\000\034\010\017\012" +
    "\010\013\005\014\006\015\004\016\020\017\012\022\021" +
    "\023\011\024\016\025\014\026\013\031\007\001\002\000" +
    "\034\010\017\012\010\013\005\014\006\015\004\016\020" +
    "\017\012\022\021\023\011\024\016\025\014\026\013\031" +
    "\007\001\002\000\026\002\ufff7\004\ufff7\005\ufff7\006\ufff7" +
    "\007\ufff7\011\ufff7\020\ufff7\021\ufff7\027\ufff7\030\ufff7\001" +
    "\002\000\034\010\017\012\010\013\005\014\006\015\004" +
    "\016\020\017\012\022\021\023\011\024\016\025\014\026" +
    "\013\031\007\001\002\000\034\010\017\012\010\013\005" +
    "\014\006\015\004\016\020\017\012\022\021\023\011\024" +
    "\016\025\014\026\013\031\007\001\002\000\034\010\017" +
    "\012\010\013\005\014\006\015\004\016\020\017\012\022" +
    "\021\023\011\024\016\025\014\026\013\031\007\001\002" +
    "\000\026\002\ufff5\004\ufff5\005\ufff5\006\ufff5\007\ufff5\011" +
    "\ufff5\020\ufff5\021\ufff5\027\026\030\ufff5\001\002\000\026" +
    "\002\ufff4\004\ufff4\005\ufff4\006\ufff4\007\ufff4\011\ufff4\020" +
    "\ufff4\021\ufff4\027\026\030\ufff4\001\002\000\026\002\ufffe" +
    "\004\ufffe\005\ufffe\006\ufffe\007\ufffe\011\ufffe\020\034\021" +
    "\033\027\026\030\030\001\002\000\026\002\uffef\004\uffef" +
    "\005\uffef\006\uffef\007\uffef\011\uffef\020\uffef\021\uffef\027" +
    "\026\030\uffef\001\002\000\026\002\001\004\001\005\001" +
    "\006\032\007\025\011\001\020\034\021\033\027\026\030" +
    "\030\001\002\000\026\002\ufffd\004\ufffd\005\ufffd\006\ufffd" +
    "\007\ufffd\011\ufffd\020\034\021\033\027\026\030\030\001" +
    "\002\000\026\002\uffff\004\uffff\005\uffff\006\032\007\025" +
    "\011\uffff\020\034\021\033\027\026\030\030\001\002\000" +
    "\024\004\027\005\024\006\032\007\025\011\045\020\034" +
    "\021\033\027\026\030\030\001\002\000\026\002\ufffc\004" +
    "\ufffc\005\ufffc\006\ufffc\007\ufffc\011\ufffc\020\ufffc\021\ufffc" +
    "\027\ufffc\030\ufffc\001\002\000\034\010\017\012\010\013" +
    "\005\014\006\015\004\016\020\017\012\022\021\023\011" +
    "\024\016\025\014\026\013\031\007\001\002\000\024\004" +
    "\027\005\024\006\032\007\025\011\050\020\034\021\033" +
    "\027\026\030\030\001\002\000\026\002\ufff3\004\ufff3\005" +
    "\ufff3\006\ufff3\007\ufff3\011\ufff3\020\ufff3\021\ufff3\027\ufff3" +
    "\030\ufff3\001\002\000\004\002\000\001\002\000\034\010" +
    "\017\012\010\013\005\014\006\015\004\016\020\017\012" +
    "\022\021\023\011\024\016\025\014\026\013\031\007\001" +
    "\002\000\024\004\027\005\024\006\032\007\025\011\054" +
    "\020\034\021\033\027\026\030\030\001\002\000\026\002" +
    "\ufff2\004\ufff2\005\ufff2\006\ufff2\007\ufff2\011\ufff2\020\ufff2" +
    "\021\ufff2\027\ufff2\030\ufff2\001\002\000\034\010\017\012" +
    "\010\013\005\014\006\015\004\016\020\017\012\022\021" +
    "\023\011\024\016\025\014\026\013\031\007\001\002\000" +
    "\024\004\027\005\024\006\032\007\025\011\057\020\034" +
    "\021\033\027\026\030\030\001\002\000\026\002\ufff1\004" +
    "\ufff1\005\ufff1\006\ufff1\007\ufff1\011\ufff1\020\ufff1\021\ufff1" +
    "\027\ufff1\030\ufff1\001\002\000\034\010\017\012\010\013" +
    "\005\014\006\015\004\016\020\017\012\022\021\023\011" +
    "\024\016\025\014\026\013\031\007\001\002\000\024\004" +
    "\027\005\024\006\032\007\025\011\062\020\034\021\033" +
    "\027\026\030\030\001\002\000\026\002\ufff6\004\ufff6\005" +
    "\ufff6\006\ufff6\007\ufff6\011\ufff6\020\ufff6\021\ufff6\027\ufff6" +
    "\030\ufff6\001\002\000\034\010\017\012\010\013\005\014" +
    "\006\015\004\016\020\017\012\022\021\023\011\024\016" +
    "\025\014\026\013\031\007\001\002\000\024\004\027\005" +
    "\024\006\032\007\025\011\065\020\034\021\033\027\026" +
    "\030\030\001\002\000\026\002\ufffb\004\ufffb\005\ufffb\006" +
    "\ufffb\007\ufffb\011\ufffb\020\ufffb\021\ufffb\027\ufffb\030\ufffb" +
    "\001\002\000\034\010\017\012\010\013\005\014\006\015" +
    "\004\016\020\017\012\022\021\023\011\024\016\025\014" +
    "\026\013\031\007\001\002\000\024\004\027\005\024\006" +
    "\032\007\025\011\070\020\034\021\033\027\026\030\030" +
    "\001\002\000\026\002\ufff9\004\ufff9\005\ufff9\006\ufff9\007" +
    "\ufff9\011\ufff9\020\ufff9\021\ufff9\027\ufff9\030\ufff9\001\002" +
    "\000\034\010\017\012\010\013\005\014\006\015\004\016" +
    "\020\017\012\022\021\023\011\024\016\025\014\026\013" +
    "\031\007\001\002\000\024\004\027\005\024\006\032\007" +
    "\025\011\073\020\034\021\033\027\026\030\030\001\002" +
    "\000\026\002\ufffa\004\ufffa\005\ufffa\006\ufffa\007\ufffa\011" +
    "\ufffa\020\ufffa\021\ufffa\027\ufffa\030\ufffa\001\002\000\034" +
    "\010\017\012\010\013\005\014\006\015\004\016\020\017" +
    "\012\022\021\023\011\024\016\025\014\026\013\031\007" +
    "\001\002\000\024\004\027\005\024\006\032\007\025\011" +
    "\076\020\034\021\033\027\026\030\030\001\002\000\026" +
    "\002\ufff8\004\ufff8\005\ufff8\006\ufff8\007\ufff8\011\ufff8\020" +
    "\ufff8\021\ufff8\027\ufff8\030\ufff8\001\002" });

  /** Access to parse-action table. */
  public short[][] action_table() {return _action_table;}

  /** <code>reduce_goto</code> table. */
  protected static final short[][] _reduce_table = 
    unpackFromStrings(new String[] {
    "\000\074\000\004\003\014\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\004\003\043\001\001\000\002\001\001\000\002\001" +
    "\001\000\004\003\022\001\001\000\002\001\001\000\004" +
    "\003\042\001\001\000\004\003\041\001\001\000\002\001" +
    "\001\000\004\003\040\001\001\000\004\003\037\001\001" +
    "\000\002\001\001\000\004\003\036\001\001\000\004\003" +
    "\035\001\001\000\004\003\034\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\004\003\046\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\004" +
    "\003\052\001\001\000\002\001\001\000\002\001\001\000" +
    "\004\003\055\001\001\000\002\001\001\000\002\001\001" +
    "\000\004\003\060\001\001\000\002\001\001\000\002\001" +
    "\001\000\004\003\063\001\001\000\002\001\001\000\002" +
    "\001\001\000\004\003\066\001\001\000\002\001\001\000" +
    "\002\001\001\000\004\003\071\001\001\000\002\001\001" +
    "\000\002\001\001\000\004\003\074\001\001\000\002\001" +
    "\001\000\002\001\001" });

  /** Access to <code>reduce_goto</code> table. */
  public short[][] reduce_table() {return _reduce_table;}

  /** Instance of action encapsulation class. */
  protected CUP$CalcParser$actions action_obj;

  /** Action encapsulation object initializer. */
  protected void init_actions()
    {
      action_obj = new CUP$CalcParser$actions(this);
    }

  /** Invoke a user supplied parse action. */
  public Symbol do_action(
    int                        act_num,
    lr_parser parser,
    java.util.Stack            stack,
    int                        top)
    throws java.lang.Exception
  {
    /* call code in generated class */
    return action_obj.CUP$CalcParser$do_action(act_num, parser, stack, top);
  }

  /** Indicates start state. */
  public int start_state() {return 0;}
  /** Indicates start production. */
  public int start_production() {return 1;}

  /** <code>EOF</code> Symbol index. */
  public int EOF_sym() {return 0;}

  /** <code>error</code> Symbol index. */
  public int error_sym() {return 1;}

}

/** Cup generated class to encapsulate user supplied action code.*/
class CUP$CalcParser$actions {
  private final CalcParser parser;

  /** Constructor */
  CUP$CalcParser$actions(CalcParser parser) {
    this.parser = parser;
  }

  /** Method with the actual generated action code. */
  public final Symbol CUP$CalcParser$do_action(
    int                        CUP$CalcParser$act_num,
    lr_parser CUP$CalcParser$parser,
    java.util.Stack            CUP$CalcParser$stack,
    int                        CUP$CalcParser$top)
    throws java.lang.Exception
    {
      /* Symbol object for return from actions */
      Symbol CUP$CalcParser$result;

      /* select the action based on the action number */
      switch (CUP$CalcParser$act_num)
        {
          /*. . . . . . . . . . . . . . . . . . . .*/
          case 21: // expr ::= NUMBER 
            {
              Double RESULT = null;
		int eleft = ((Symbol)CUP$CalcParser$stack.elementAt(CUP$CalcParser$top-0)).left;
		int eright = ((Symbol)CUP$CalcParser$stack.elementAt(CUP$CalcParser$top-0)).right;
		Double e = (Double)((Symbol) CUP$CalcParser$stack.elementAt(CUP$CalcParser$top-0)).value;
		 RESULT = e; 
              CUP$CalcParser$result = new Symbol(1/*expr*/, ((Symbol)CUP$CalcParser$stack.elementAt(CUP$CalcParser$top-0)).left, ((Symbol)CUP$CalcParser$stack.elementAt(CUP$CalcParser$top-0)).right, RESULT);
            }
          return CUP$CalcParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 20: // expr ::= NATURAL 
            {
              Double RESULT = null;
		int eleft = ((Symbol)CUP$CalcParser$stack.elementAt(CUP$CalcParser$top-0)).left;
		int eright = ((Symbol)CUP$CalcParser$stack.elementAt(CUP$CalcParser$top-0)).right;
		Object e = (Object)((Symbol) CUP$CalcParser$stack.elementAt(CUP$CalcParser$top-0)).value;
		 RESULT = Math.E; 
              CUP$CalcParser$result = new Symbol(1/*expr*/, ((Symbol)CUP$CalcParser$stack.elementAt(CUP$CalcParser$top-0)).left, ((Symbol)CUP$CalcParser$stack.elementAt(CUP$CalcParser$top-0)).right, RESULT);
            }
          return CUP$CalcParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 19: // expr ::= PI 
            {
              Double RESULT = null;
		int eleft = ((Symbol)CUP$CalcParser$stack.elementAt(CUP$CalcParser$top-0)).left;
		int eright = ((Symbol)CUP$CalcParser$stack.elementAt(CUP$CalcParser$top-0)).right;
		Object e = (Object)((Symbol) CUP$CalcParser$stack.elementAt(CUP$CalcParser$top-0)).value;
		 RESULT = Math.PI; 
              CUP$CalcParser$result = new Symbol(1/*expr*/, ((Symbol)CUP$CalcParser$stack.elementAt(CUP$CalcParser$top-0)).left, ((Symbol)CUP$CalcParser$stack.elementAt(CUP$CalcParser$top-0)).right, RESULT);
            }
          return CUP$CalcParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 18: // expr ::= expr ROOT expr 
            {
              Double RESULT = null;
		int e1left = ((Symbol)CUP$CalcParser$stack.elementAt(CUP$CalcParser$top-2)).left;
		int e1right = ((Symbol)CUP$CalcParser$stack.elementAt(CUP$CalcParser$top-2)).right;
		Double e1 = (Double)((Symbol) CUP$CalcParser$stack.elementAt(CUP$CalcParser$top-2)).value;
		int e2left = ((Symbol)CUP$CalcParser$stack.elementAt(CUP$CalcParser$top-0)).left;
		int e2right = ((Symbol)CUP$CalcParser$stack.elementAt(CUP$CalcParser$top-0)).right;
		Double e2 = (Double)((Symbol) CUP$CalcParser$stack.elementAt(CUP$CalcParser$top-0)).value;
		 RESULT = Math.pow(Math.exp (1/e1.doubleValue()),Math.log(e2.doubleValue())); 
              CUP$CalcParser$result = new Symbol(1/*expr*/, ((Symbol)CUP$CalcParser$stack.elementAt(CUP$CalcParser$top-2)).left, ((Symbol)CUP$CalcParser$stack.elementAt(CUP$CalcParser$top-0)).right, RESULT);
            }
          return CUP$CalcParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 17: // expr ::= expr PERCENTAGE 
            {
              Double RESULT = null;
		int eleft = ((Symbol)CUP$CalcParser$stack.elementAt(CUP$CalcParser$top-1)).left;
		int eright = ((Symbol)CUP$CalcParser$stack.elementAt(CUP$CalcParser$top-1)).right;
		Double e = (Double)((Symbol) CUP$CalcParser$stack.elementAt(CUP$CalcParser$top-1)).value;
		 RESULT = new Double(e.doubleValue() / 100.0); 
              CUP$CalcParser$result = new Symbol(1/*expr*/, ((Symbol)CUP$CalcParser$stack.elementAt(CUP$CalcParser$top-1)).left, ((Symbol)CUP$CalcParser$stack.elementAt(CUP$CalcParser$top-0)).right, RESULT);
            }
          return CUP$CalcParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 16: // expr ::= TANINV LPAREN expr RPAREN 
            {
              Double RESULT = null;
		int eleft = ((Symbol)CUP$CalcParser$stack.elementAt(CUP$CalcParser$top-1)).left;
		int eright = ((Symbol)CUP$CalcParser$stack.elementAt(CUP$CalcParser$top-1)).right;
		Double e = (Double)((Symbol) CUP$CalcParser$stack.elementAt(CUP$CalcParser$top-1)).value;
		 RESULT = Math.atan( e ); 
              CUP$CalcParser$result = new Symbol(1/*expr*/, ((Symbol)CUP$CalcParser$stack.elementAt(CUP$CalcParser$top-3)).left, ((Symbol)CUP$CalcParser$stack.elementAt(CUP$CalcParser$top-0)).right, RESULT);
            }
          return CUP$CalcParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 15: // expr ::= SININV LPAREN expr RPAREN 
            {
              Double RESULT = null;
		int eleft = ((Symbol)CUP$CalcParser$stack.elementAt(CUP$CalcParser$top-1)).left;
		int eright = ((Symbol)CUP$CalcParser$stack.elementAt(CUP$CalcParser$top-1)).right;
		Double e = (Double)((Symbol) CUP$CalcParser$stack.elementAt(CUP$CalcParser$top-1)).value;
		 RESULT = Math.asin( e ); 
              CUP$CalcParser$result = new Symbol(1/*expr*/, ((Symbol)CUP$CalcParser$stack.elementAt(CUP$CalcParser$top-3)).left, ((Symbol)CUP$CalcParser$stack.elementAt(CUP$CalcParser$top-0)).right, RESULT);
            }
          return CUP$CalcParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 14: // expr ::= COSINV LPAREN expr RPAREN 
            {
              Double RESULT = null;
		int eleft = ((Symbol)CUP$CalcParser$stack.elementAt(CUP$CalcParser$top-1)).left;
		int eright = ((Symbol)CUP$CalcParser$stack.elementAt(CUP$CalcParser$top-1)).right;
		Double e = (Double)((Symbol) CUP$CalcParser$stack.elementAt(CUP$CalcParser$top-1)).value;
		 RESULT = Math.acos( e ); 
              CUP$CalcParser$result = new Symbol(1/*expr*/, ((Symbol)CUP$CalcParser$stack.elementAt(CUP$CalcParser$top-3)).left, ((Symbol)CUP$CalcParser$stack.elementAt(CUP$CalcParser$top-0)).right, RESULT);
            }
          return CUP$CalcParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 13: // expr ::= expr EXPONENT expr 
            {
              Double RESULT = null;
		int e1left = ((Symbol)CUP$CalcParser$stack.elementAt(CUP$CalcParser$top-2)).left;
		int e1right = ((Symbol)CUP$CalcParser$stack.elementAt(CUP$CalcParser$top-2)).right;
		Double e1 = (Double)((Symbol) CUP$CalcParser$stack.elementAt(CUP$CalcParser$top-2)).value;
		int e2left = ((Symbol)CUP$CalcParser$stack.elementAt(CUP$CalcParser$top-0)).left;
		int e2right = ((Symbol)CUP$CalcParser$stack.elementAt(CUP$CalcParser$top-0)).right;
		Double e2 = (Double)((Symbol) CUP$CalcParser$stack.elementAt(CUP$CalcParser$top-0)).value;
		 RESULT = new Double(Math.pow(e1.doubleValue(), e2.doubleValue())); 
              CUP$CalcParser$result = new Symbol(1/*expr*/, ((Symbol)CUP$CalcParser$stack.elementAt(CUP$CalcParser$top-2)).left, ((Symbol)CUP$CalcParser$stack.elementAt(CUP$CalcParser$top-0)).right, RESULT);
            }
          return CUP$CalcParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 12: // expr ::= expr EXP expr 
            {
              Double RESULT = null;
		int e1left = ((Symbol)CUP$CalcParser$stack.elementAt(CUP$CalcParser$top-2)).left;
		int e1right = ((Symbol)CUP$CalcParser$stack.elementAt(CUP$CalcParser$top-2)).right;
		Double e1 = (Double)((Symbol) CUP$CalcParser$stack.elementAt(CUP$CalcParser$top-2)).value;
		int e2left = ((Symbol)CUP$CalcParser$stack.elementAt(CUP$CalcParser$top-0)).left;
		int e2right = ((Symbol)CUP$CalcParser$stack.elementAt(CUP$CalcParser$top-0)).right;
		Double e2 = (Double)((Symbol) CUP$CalcParser$stack.elementAt(CUP$CalcParser$top-0)).value;
		 RESULT = new Double(e1.doubleValue() * Math.pow(10, e2.doubleValue())); 
              CUP$CalcParser$result = new Symbol(1/*expr*/, ((Symbol)CUP$CalcParser$stack.elementAt(CUP$CalcParser$top-2)).left, ((Symbol)CUP$CalcParser$stack.elementAt(CUP$CalcParser$top-0)).right, RESULT);
            }
          return CUP$CalcParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 11: // expr ::= SQRT LPAREN expr RPAREN 
            {
              Double RESULT = null;
		int eleft = ((Symbol)CUP$CalcParser$stack.elementAt(CUP$CalcParser$top-1)).left;
		int eright = ((Symbol)CUP$CalcParser$stack.elementAt(CUP$CalcParser$top-1)).right;
		Double e = (Double)((Symbol) CUP$CalcParser$stack.elementAt(CUP$CalcParser$top-1)).value;
		 RESULT = Math.sqrt( e ); 
              CUP$CalcParser$result = new Symbol(1/*expr*/, ((Symbol)CUP$CalcParser$stack.elementAt(CUP$CalcParser$top-3)).left, ((Symbol)CUP$CalcParser$stack.elementAt(CUP$CalcParser$top-0)).right, RESULT);
            }
          return CUP$CalcParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 10: // expr ::= LOG LPAREN expr RPAREN 
            {
              Double RESULT = null;
		int eleft = ((Symbol)CUP$CalcParser$stack.elementAt(CUP$CalcParser$top-1)).left;
		int eright = ((Symbol)CUP$CalcParser$stack.elementAt(CUP$CalcParser$top-1)).right;
		Double e = (Double)((Symbol) CUP$CalcParser$stack.elementAt(CUP$CalcParser$top-1)).value;
		 RESULT = Math.log( e ) / Math.log( 10 ); 
              CUP$CalcParser$result = new Symbol(1/*expr*/, ((Symbol)CUP$CalcParser$stack.elementAt(CUP$CalcParser$top-3)).left, ((Symbol)CUP$CalcParser$stack.elementAt(CUP$CalcParser$top-0)).right, RESULT);
            }
          return CUP$CalcParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 9: // expr ::= LN LPAREN expr RPAREN 
            {
              Double RESULT = null;
		int eleft = ((Symbol)CUP$CalcParser$stack.elementAt(CUP$CalcParser$top-1)).left;
		int eright = ((Symbol)CUP$CalcParser$stack.elementAt(CUP$CalcParser$top-1)).right;
		Double e = (Double)((Symbol) CUP$CalcParser$stack.elementAt(CUP$CalcParser$top-1)).value;
		 RESULT = Math.log( e ) / Math.log( Math.E ); 
              CUP$CalcParser$result = new Symbol(1/*expr*/, ((Symbol)CUP$CalcParser$stack.elementAt(CUP$CalcParser$top-3)).left, ((Symbol)CUP$CalcParser$stack.elementAt(CUP$CalcParser$top-0)).right, RESULT);
            }
          return CUP$CalcParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 8: // expr ::= TAN LPAREN expr RPAREN 
            {
              Double RESULT = null;
		int eleft = ((Symbol)CUP$CalcParser$stack.elementAt(CUP$CalcParser$top-1)).left;
		int eright = ((Symbol)CUP$CalcParser$stack.elementAt(CUP$CalcParser$top-1)).right;
		Double e = (Double)((Symbol) CUP$CalcParser$stack.elementAt(CUP$CalcParser$top-1)).value;
		 RESULT = Math.tan( e ); 
              CUP$CalcParser$result = new Symbol(1/*expr*/, ((Symbol)CUP$CalcParser$stack.elementAt(CUP$CalcParser$top-3)).left, ((Symbol)CUP$CalcParser$stack.elementAt(CUP$CalcParser$top-0)).right, RESULT);
            }
          return CUP$CalcParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 7: // expr ::= SIN LPAREN expr RPAREN 
            {
              Double RESULT = null;
		int eleft = ((Symbol)CUP$CalcParser$stack.elementAt(CUP$CalcParser$top-1)).left;
		int eright = ((Symbol)CUP$CalcParser$stack.elementAt(CUP$CalcParser$top-1)).right;
		Double e = (Double)((Symbol) CUP$CalcParser$stack.elementAt(CUP$CalcParser$top-1)).value;
		 RESULT = Math.sin( e ); 
              CUP$CalcParser$result = new Symbol(1/*expr*/, ((Symbol)CUP$CalcParser$stack.elementAt(CUP$CalcParser$top-3)).left, ((Symbol)CUP$CalcParser$stack.elementAt(CUP$CalcParser$top-0)).right, RESULT);
            }
          return CUP$CalcParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 6: // expr ::= COS LPAREN expr RPAREN 
            {
              Double RESULT = null;
		int eleft = ((Symbol)CUP$CalcParser$stack.elementAt(CUP$CalcParser$top-1)).left;
		int eright = ((Symbol)CUP$CalcParser$stack.elementAt(CUP$CalcParser$top-1)).right;
		Double e = (Double)((Symbol) CUP$CalcParser$stack.elementAt(CUP$CalcParser$top-1)).value;
		 RESULT = Math.cos( e ); 
              CUP$CalcParser$result = new Symbol(1/*expr*/, ((Symbol)CUP$CalcParser$stack.elementAt(CUP$CalcParser$top-3)).left, ((Symbol)CUP$CalcParser$stack.elementAt(CUP$CalcParser$top-0)).right, RESULT);
            }
          return CUP$CalcParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 5: // expr ::= LPAREN expr RPAREN 
            {
              Double RESULT = null;
		int eleft = ((Symbol)CUP$CalcParser$stack.elementAt(CUP$CalcParser$top-1)).left;
		int eright = ((Symbol)CUP$CalcParser$stack.elementAt(CUP$CalcParser$top-1)).right;
		Double e = (Double)((Symbol) CUP$CalcParser$stack.elementAt(CUP$CalcParser$top-1)).value;
		 RESULT = e; 
              CUP$CalcParser$result = new Symbol(1/*expr*/, ((Symbol)CUP$CalcParser$stack.elementAt(CUP$CalcParser$top-2)).left, ((Symbol)CUP$CalcParser$stack.elementAt(CUP$CalcParser$top-0)).right, RESULT);
            }
          return CUP$CalcParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 4: // expr ::= expr DIVIDE expr 
            {
              Double RESULT = null;
		int e1left = ((Symbol)CUP$CalcParser$stack.elementAt(CUP$CalcParser$top-2)).left;
		int e1right = ((Symbol)CUP$CalcParser$stack.elementAt(CUP$CalcParser$top-2)).right;
		Double e1 = (Double)((Symbol) CUP$CalcParser$stack.elementAt(CUP$CalcParser$top-2)).value;
		int e2left = ((Symbol)CUP$CalcParser$stack.elementAt(CUP$CalcParser$top-0)).left;
		int e2right = ((Symbol)CUP$CalcParser$stack.elementAt(CUP$CalcParser$top-0)).right;
		Double e2 = (Double)((Symbol) CUP$CalcParser$stack.elementAt(CUP$CalcParser$top-0)).value;
		 RESULT = new Double(e1.doubleValue() / e2.doubleValue()); 
              CUP$CalcParser$result = new Symbol(1/*expr*/, ((Symbol)CUP$CalcParser$stack.elementAt(CUP$CalcParser$top-2)).left, ((Symbol)CUP$CalcParser$stack.elementAt(CUP$CalcParser$top-0)).right, RESULT);
            }
          return CUP$CalcParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 3: // expr ::= expr TIMES expr 
            {
              Double RESULT = null;
		int e1left = ((Symbol)CUP$CalcParser$stack.elementAt(CUP$CalcParser$top-2)).left;
		int e1right = ((Symbol)CUP$CalcParser$stack.elementAt(CUP$CalcParser$top-2)).right;
		Double e1 = (Double)((Symbol) CUP$CalcParser$stack.elementAt(CUP$CalcParser$top-2)).value;
		int e2left = ((Symbol)CUP$CalcParser$stack.elementAt(CUP$CalcParser$top-0)).left;
		int e2right = ((Symbol)CUP$CalcParser$stack.elementAt(CUP$CalcParser$top-0)).right;
		Double e2 = (Double)((Symbol) CUP$CalcParser$stack.elementAt(CUP$CalcParser$top-0)).value;
		 RESULT = new Double(e1.doubleValue() * e2.doubleValue()); 
              CUP$CalcParser$result = new Symbol(1/*expr*/, ((Symbol)CUP$CalcParser$stack.elementAt(CUP$CalcParser$top-2)).left, ((Symbol)CUP$CalcParser$stack.elementAt(CUP$CalcParser$top-0)).right, RESULT);
            }
          return CUP$CalcParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 2: // expr ::= expr MINUS expr 
            {
              Double RESULT = null;
		int e1left = ((Symbol)CUP$CalcParser$stack.elementAt(CUP$CalcParser$top-2)).left;
		int e1right = ((Symbol)CUP$CalcParser$stack.elementAt(CUP$CalcParser$top-2)).right;
		Double e1 = (Double)((Symbol) CUP$CalcParser$stack.elementAt(CUP$CalcParser$top-2)).value;
		int e2left = ((Symbol)CUP$CalcParser$stack.elementAt(CUP$CalcParser$top-0)).left;
		int e2right = ((Symbol)CUP$CalcParser$stack.elementAt(CUP$CalcParser$top-0)).right;
		Double e2 = (Double)((Symbol) CUP$CalcParser$stack.elementAt(CUP$CalcParser$top-0)).value;
		 RESULT = new Double(e1.doubleValue() - e2.doubleValue()); 
              CUP$CalcParser$result = new Symbol(1/*expr*/, ((Symbol)CUP$CalcParser$stack.elementAt(CUP$CalcParser$top-2)).left, ((Symbol)CUP$CalcParser$stack.elementAt(CUP$CalcParser$top-0)).right, RESULT);
            }
          return CUP$CalcParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 1: // $START ::= expr EOF 
            {
              Object RESULT = null;
		int start_valleft = ((Symbol)CUP$CalcParser$stack.elementAt(CUP$CalcParser$top-1)).left;
		int start_valright = ((Symbol)CUP$CalcParser$stack.elementAt(CUP$CalcParser$top-1)).right;
		Double start_val = (Double)((Symbol) CUP$CalcParser$stack.elementAt(CUP$CalcParser$top-1)).value;
		RESULT = start_val;
              CUP$CalcParser$result = new Symbol(0/*$START*/, ((Symbol)CUP$CalcParser$stack.elementAt(CUP$CalcParser$top-1)).left, ((Symbol)CUP$CalcParser$stack.elementAt(CUP$CalcParser$top-0)).right, RESULT);
            }
          /* ACCEPT */
          CUP$CalcParser$parser.done_parsing();
          return CUP$CalcParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 0: // expr ::= expr PLUS expr 
            {
              Double RESULT = null;
		int e1left = ((Symbol)CUP$CalcParser$stack.elementAt(CUP$CalcParser$top-2)).left;
		int e1right = ((Symbol)CUP$CalcParser$stack.elementAt(CUP$CalcParser$top-2)).right;
		Double e1 = (Double)((Symbol) CUP$CalcParser$stack.elementAt(CUP$CalcParser$top-2)).value;
		int e2left = ((Symbol)CUP$CalcParser$stack.elementAt(CUP$CalcParser$top-0)).left;
		int e2right = ((Symbol)CUP$CalcParser$stack.elementAt(CUP$CalcParser$top-0)).right;
		Double e2 = (Double)((Symbol) CUP$CalcParser$stack.elementAt(CUP$CalcParser$top-0)).value;
		 RESULT = new Double(e1.doubleValue() + e2.doubleValue()); 
              CUP$CalcParser$result = new Symbol(1/*expr*/, ((Symbol)CUP$CalcParser$stack.elementAt(CUP$CalcParser$top-2)).left, ((Symbol)CUP$CalcParser$stack.elementAt(CUP$CalcParser$top-0)).right, RESULT);
            }
          return CUP$CalcParser$result;

          /* . . . . . .*/
          default:
            throw new Exception(
               "Invalid action number found in internal parse table");

        }
    }
}

