package com.constaapps.constacalc.ui.main;
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Tue May 21 21:42:49 EDT 2019
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class CalcSymbol {
  /* terminals */
  public static final int ROOT = 22;
  public static final int TIMES = 4;
  public static final int NATURAL = 17;
  public static final int SIN = 9;
  public static final int PLUS = 2;
  public static final int RPAREN = 7;
  public static final int SININVDEG = 29;
  public static final int COS = 8;
  public static final int LN = 11;
  public static final int COSDEG = 25;
  public static final int EXPONENT = 15;
  public static final int SINDEG = 26;
  public static final int SQRT = 13;
  public static final int LPAREN = 6;
  public static final int LOG = 12;
  public static final int EXP = 14;
  public static final int TANDEG = 27;
  public static final int NUMBER = 31;
  public static final int EOF = 0;
  public static final int DIVIDE = 5;
  public static final int COSINVDEG = 28;
  public static final int TANINVDEG = 30;
  public static final int NEGATE = 23;
  public static final int PERCENTAGE = 21;
  public static final int PI = 16;
  public static final int MINUS = 3;
  public static final int error = 1;
  public static final int COSINV = 18;
  public static final int SININV = 19;
  public static final int TAN = 10;
  public static final int ABSOLUTE = 24;
  public static final int TANINV = 20;
}

